// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/air-quality-redesign/AirQualityRedesign.tsx": () => import("../components/mockups/air-quality-redesign/AirQualityRedesign.tsx"),
  "./components/mockups/uv-forecast-redesign/UVForecastRedesign.tsx": () => import("../components/mockups/uv-forecast-redesign/UVForecastRedesign.tsx")
};
